on:
  push:
    branches:
      - master

jobs:
  export_game:
    # Always use ubuntu-latest for this action
    runs-on: ubuntu-latest
    # Job name, can be anything
    name: Export game to Github
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.1
        # Ensure that you get the entire project history
        with:
          fetch-depth: 0
      - name: zip the folder structure
          uses: montudor/action-zip@v0.1.0
          with:
            args: zip -qq -r game.zip ./
    relative_project_path: .
    env:
      GITHUB_TOKEN: ${{ secrets.GH_CREDENTIALS }}
